### ISSUE TITLE
Unplayable on mobile :P

### ISSUE THREAD

**Issue by Bavuett** [caamillo/swear-wordle#1]
Cool project, but it would have been cooler if it had a keyboard so people can play it on mobile too. :)

**Comment by caamillo** [comment]
Si fra lo so, sto progetto era semplicemente una roba nata per uno "speedcoding" asmr su youtube (tra virgolette perchè alla fine sono stato lento) e se vedi tra i [TODO](https://github.com/caamillo/swear-wordle/blob/main/.TODO) avevo aggiunto la spunta di aggiungere il mobile responsive.
